[libraries]
# plugin
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version = "1.8.22" }
ktlint-gradle = { module = "org.jlleitschuh.gradle:ktlint-gradle", version = "11.3.2" }
plugin-publish-plugin = { module = "com.gradle.publish:plugin-publish-plugin", version = "1.2.0" }

# BOM
kotest-bom = { module = "io.kotest:kotest-bom", version = "5.6.2" }
